# Generated by Django 3.2.7 on 2022-04-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220416_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('HOME', 'HOME'), ('OFFICE', 'OFFICE')], default='HOME', max_length=20),
        ),
    ]
